### ISSUE TITLE
Collaboration with other SilverStripe Plugin

### ISSUE THREAD

**Issue by Chris2011** [jdemeschew/stpnb#2]
I found another plugin: https://github.com/guru-digital/sstemplate-netbeans. In your plugin the problem is the templating strings are not very colorful AND the biggest problem is the broken HTML code completion. He solved the problem. Maybe you can work together to bring it to a big nice plugin. He solved problems and you have this include feature etc. Would be great. :)

**Comment by cjsewell** [comment]
Sounds like a great plan - Things have been very busy for me lately and I not had the time to develop my module further - but I am more than happy to provide assistance and accept pull requests until I get some time to continue myself!

**Comment by Chris2011** [comment]
No problem, sounds great that you are interested :). For the first time, this is enough and if you have time, you can help and vice versa :)

**Comment by Chris2011** [comment]
Anything new here?

**Comment by zaumniks** [comment]
hibernating at the moment
